"""
Cross-Perturbation MoA Framework -- Model Architecture (v2)

Key improvements over v1:
1. RFCFPDrugEncoder: FCFP fingerprint-based drug encoding (unseen compound support)
2. MetricMoAHead: Prototype-based zero-shot MoA classification
3. Shared latent space for CRISPR + drug perturbations

Architecture components:
1. PerturbationEncoder: CRISPR gene perturbation (index-based, known targets)
2. RFCFPDrugEncoder: Drug perturbation via FCFP fingerprint + dose (unseen compound OK)
3. BasalEncoder: Cell basal state from gene expression
4. CovariateEncoder: Cell line / batch covariate
5. CellStateDecoder: Reconstruct gene expression
6. MoAClassificationHead: Supervised MoA classification (seen classes)
7. MetricMoAHead: Prototype-based zero-shot MoA (unseen classes via nearest prototype)
8. MoAContrastiveLoss: MoA-aware contrastive learning
9. AdversarialDiscriminator: Disentangle perturbation from covariate
"""
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from config import ModelConfig


class PerturbationEncoder(nn.Module):
    """
    Encodes CRISPR perturbation information via gene index embedding.

    For CRISPR perturbations, gene targets are known a priori, so index-based
    embedding is appropriate (unlike drugs where structure matters for generalization).
    """

    def __init__(self, n_perturbations: int, latent_dim: int = 32,
                 hidden_dims: list = None):
        super().__init__()
        self.latent_dim = latent_dim
        self.perturb_embedding = nn.Embedding(n_perturbations, latent_dim)

        hidden_dims = hidden_dims or [64]
        layers = []
        prev_dim = latent_dim
        for h_dim in hidden_dims:
            layers.extend([
                nn.Linear(prev_dim, h_dim),
                nn.BatchNorm1d(h_dim),
                nn.ReLU(),
                nn.Dropout(0.1),
            ])
            prev_dim = h_dim
        layers.append(nn.Linear(prev_dim, latent_dim))
        self.mlp = nn.Sequential(*layers)

    def forward(self, perturb_idx: torch.Tensor):
        """
        Args:
            perturb_idx: [batch_size] CRISPR gene target indices
        Returns:
            z_perturb: [batch_size, latent_dim]
        """
        z = self.perturb_embedding(perturb_idx)
        return self.mlp(z)


class RFCFPDrugEncoder(nn.Module):
    """
    Encodes drug perturbation via FCFP fingerprint + dose (rFCFP).

    Key design: fingerprint * log10(dose+1) as in PRnet (Lotfollahi et al. 2023).
    This enables generalization to unseen compounds -- their chemical structure
    (fingerprint) directly produces a meaningful latent representation.

    For synthetic data without real SMILES: use MoA-correlated random fingerprints
    generated by data_utils.generate_synthetic_fingerprints().
    For real data: use RDKit to compute FCFP from SMILES.
    """

    def __init__(self, fingerprint_bits: int = 1024, latent_dim: int = 32,
                 hidden_dims: list = None):
        super().__init__()
        self.fingerprint_bits = fingerprint_bits
        self.latent_dim = latent_dim

        # rFCFP input: fingerprint * dose_scaling -> same dimension as fingerprint
        # Then MLP projects to latent_dim
        hidden_dims = hidden_dims or [256, 128]
        layers = []
        prev_dim = fingerprint_bits
        for h_dim in hidden_dims:
            layers.extend([
                nn.Linear(prev_dim, h_dim),
                nn.BatchNorm1d(h_dim),
                nn.ReLU(),
                nn.Dropout(0.1),
            ])
            prev_dim = h_dim
        layers.append(nn.Linear(prev_dim, latent_dim))
        self.mlp = nn.Sequential(*layers)

    def forward(self, fingerprint: torch.Tensor, dose: torch.Tensor = None):
        """
        Args:
            fingerprint: [batch_size, fingerprint_bits] FCFP bit vector
            dose: [batch_size, 1] dose values
        Returns:
            z_drug: [batch_size, latent_dim]
        """
        # rFCFP: fingerprint * log10(dose+1)
        if dose is not None:
            dose_scaled = torch.log10(dose + 1)  # [batch, 1]
            rfcfp = fingerprint * dose_scaled  # broadcast [batch, fp_bits]
        else:
            rfcfp = fingerprint

        z_drug = self.mlp(rfcfp)
        return z_drug


class BasalEncoder(nn.Module):
    """Encodes the basal (unperturbed) cell state from gene expression."""

    def __init__(self, n_genes: int, basal_dim: int = 64,
                 hidden_dims: list = None):
        super().__init__()
        hidden_dims = hidden_dims or [512, 256]
        layers = []
        prev_dim = n_genes
        for h_dim in hidden_dims:
            layers.extend([
                nn.Linear(prev_dim, h_dim),
                nn.BatchNorm1d(h_dim),
                nn.ReLU(),
                nn.Dropout(0.1),
            ])
            prev_dim = h_dim
        layers.append(nn.Linear(prev_dim, basal_dim))
        self.encoder = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor):
        return self.encoder(x)


class CovariateEncoder(nn.Module):
    """Encodes covariate information (cell line, batch, etc.)."""

    def __init__(self, n_covariates: int, covariate_dim: int = 16):
        super().__init__()
        self.embedding = nn.Embedding(n_covariates, covariate_dim)

    def forward(self, covariate_idx: torch.Tensor):
        return self.embedding(covariate_idx)


class CellStateDecoder(nn.Module):
    """Decodes latent representation back to gene expression space."""

    def __init__(self, input_dim: int, n_genes: int, hidden_dims: list = None):
        super().__init__()
        hidden_dims = hidden_dims or [256, 512]
        layers = []
        prev_dim = input_dim
        for h_dim in hidden_dims:
            layers.extend([
                nn.Linear(prev_dim, h_dim),
                nn.BatchNorm1d(h_dim),
                nn.ReLU(),
                nn.Dropout(0.1),
            ])
            prev_dim = h_dim
        layers.append(nn.Linear(prev_dim, n_genes))
        self.decoder = nn.Sequential(*layers)

    def forward(self, z: torch.Tensor):
        return self.decoder(z)


class AdversarialDiscriminator(nn.Module):
    """Adversarial discriminator for perturbation-covariate disentanglement."""

    def __init__(self, perturbation_dim: int = 32, n_covariates: int = 3,
                 hidden_dims: list = None):
        super().__init__()
        hidden_dims = hidden_dims or [64, 32]
        layers = []
        prev_dim = perturbation_dim
        for h_dim in hidden_dims:
            layers.extend([
                nn.Linear(prev_dim, h_dim),
                nn.ReLU(),
            ])
            prev_dim = h_dim
        layers.append(nn.Linear(prev_dim, n_covariates))
        self.discriminator = nn.Sequential(*layers)

    def forward(self, z_perturb: torch.Tensor):
        return self.discriminator(z_perturb)


class MoAClassificationHead(nn.Module):
    """Supervised MoA classification from perturbation latent vector (seen classes only)."""

    def __init__(self, perturbation_dim: int = 32, n_moa_classes: int = 10,
                 hidden_dims: list = None):
        super().__init__()
        hidden_dims = hidden_dims or [64]
        layers = []
        prev_dim = perturbation_dim
        for h_dim in hidden_dims:
            layers.extend([
                nn.Linear(prev_dim, h_dim),
                nn.ReLU(),
                nn.Dropout(0.2),
            ])
            prev_dim = h_dim
        layers.append(nn.Linear(prev_dim, n_moa_classes))
        self.classifier = nn.Sequential(*layers)

    def forward(self, z_perturb: torch.Tensor):
        return self.classifier(z_perturb)


class MetricMoAHead(nn.Module):
    """
    Prototype-based MoA classification for zero-shot generalization.

    Maintains learnable class prototypes in latent space. During inference,
    assigns MoA by nearest prototype (cosine similarity). This enables:
    - Better generalization to unseen compounds (same MoA → same prototype region)
    - Zero-shot MoA for leave-MoA-out: new MoA classes form clusters via
      contrastive learning, and nearest-neighbor matching works even without
      a classification head output for that class.

    Training: update prototypes via EMA of class mean embeddings.
    Inference: softmax over cosine similarities to prototypes (temperature-scaled).
    """

    def __init__(self, perturbation_dim: int, n_moa_classes: int,
                 temperature: float = 0.1, momentum: float = 0.9):
        super().__init__()
        self.perturbation_dim = perturbation_dim
        self.n_moa_classes = n_moa_classes
        self.temperature = temperature
        self.momentum = momentum

        # Learnable prototypes: [n_moa_classes, perturbation_dim]
        self.prototypes = nn.Parameter(
            torch.randn(n_moa_classes, perturbation_dim) * 0.01
        )
        self.register_buffer('prototype_counts', torch.zeros(n_moa_classes))

    def update_prototypes(self, z: torch.Tensor, labels: torch.Tensor):
        """Update prototypes with EMA of class mean embeddings (call during training)."""
        with torch.no_grad():
            z_norm = F.normalize(z, dim=-1)
            for c in range(self.n_moa_classes):
                mask = (labels == c)
                if mask.any():
                    class_mean = z_norm[mask].mean(dim=0)
                    if self.prototype_counts[c] == 0:
                        self.prototypes.data[c] = class_mean
                    else:
                        self.prototypes.data[c] = (
                            self.momentum * self.prototypes.data[c]
                            + (1 - self.momentum) * class_mean
                        )
                    self.prototype_counts[c] += 1

    def forward(self, z_perturb: torch.Tensor):
        """
        Compute logits as cosine similarity to prototypes, scaled by temperature.

        Args:
            z_perturb: [batch_size, perturbation_dim]
        Returns:
            logits: [batch_size, n_moa_classes] (for cross-entropy loss)
        """
        z_norm = F.normalize(z_perturb, dim=-1)
        proto_norm = F.normalize(self.prototypes, dim=-1)
        # Cosine similarity: [batch, n_moa]
        sim = torch.mm(z_norm, proto_norm.t())
        logits = sim / self.temperature
        return logits

    def predict_zero_shot(self, z_perturb: torch.Tensor,
                          reference_z: torch.Tensor = None,
                          reference_labels: torch.Tensor = None,
                          top_k: int = 1):
        """
        Zero-shot MoA prediction via nearest-neighbor in latent space.

        For truly unseen MoA classes (not in prototypes), find nearest
        reference sample in latent space and return its MoA label.

        Args:
            z_perturb: [n_query, perturbation_dim] query embeddings
            reference_z: [n_ref, perturbation_dim] reference embeddings
            reference_labels: [n_ref] MoA labels for references
            top_k: number of nearest neighbors
        Returns:
            predicted_moa: [n_query, top_k] predicted MoA labels
            similarities: [n_query, top_k] cosine similarities
        """
        z_norm = F.normalize(z_perturb, dim=-1)

        if reference_z is not None and reference_labels is not None:
            ref_norm = F.normalize(reference_z, dim=-1)
            sim = torch.mm(z_norm, ref_norm.t())
            topk_sim, topk_idx = sim.topk(top_k, dim=-1)
            predicted_moa = reference_labels[topk_idx]
            return predicted_moa, topk_sim
        else:
            # Fall back to prototype matching
            proto_norm = F.normalize(self.prototypes, dim=-1)
            sim = torch.mm(z_norm, proto_norm.t())
            topk_sim, topk_idx = sim.topk(top_k, dim=-1)
            return topk_idx, topk_sim


class MoAContrastiveLoss(nn.Module):
    """
    MoA-aware contrastive loss.

    Same MoA → pull together in latent space
    Different MoA → push apart
    """

    def __init__(self, temperature: float = 0.1, alpha: float = 2.0):
        super().__init__()
        self.temperature = temperature
        self.alpha = alpha

    def forward(self, z: torch.Tensor, labels: torch.Tensor):
        """Vectorized MoA-aware contrastive loss."""
        batch_size = z.shape[0]
        if batch_size < 2:
            return torch.tensor(0.0, device=z.device)

        z = F.normalize(z, dim=-1)
        dist_mat = torch.cdist(z, z, p=2) ** 2

        label_eq = labels.unsqueeze(0) == labels.unsqueeze(1)
        mask_pos = label_eq & ~torch.eye(batch_size, dtype=torch.bool, device=z.device)

        if mask_pos.any():
            alignment_loss = dist_mat[mask_pos].mean()
        else:
            alignment_loss = torch.tensor(0.0, device=z.device)

        sq_pdist = torch.pdist(z, p=2) ** 2
        uniformity_loss = torch.log(torch.mean(torch.exp(-self.alpha * sq_pdist)) + 1e-8)

        return alignment_loss + uniformity_loss


class CrossPerturbMoAModel(nn.Module):
    """
    Cross-Perturbation MoA Framework v2

    Key changes from v1:
    - RFCFPDrugEncoder: fingerprint-based drug encoding (unseen compound support)
    - MetricMoAHead: prototype-based zero-shot MoA (unseen MoA class support)
    - Both CRISPR and drug perturbations map to same perturbation_dim
    """

    def __init__(self, n_genes: int, n_perturbations: int, n_covariates: int,
                 n_moa_classes: int, config: ModelConfig = None,
                 fingerprint_bits: int = 1024):
        super().__init__()
        self.config = config or ModelConfig()
        c = self.config
        self.fingerprint_bits = fingerprint_bits

        # Drug encoder (rFCFP-based)
        self.drug_encoder = RFCFPDrugEncoder(
            fingerprint_bits=fingerprint_bits,
            latent_dim=c.perturbation_dim,
            hidden_dims=c.drug_hidden_dims,
        )

        # CRISPR perturbation encoder (index-based)
        self.crispr_encoder = PerturbationEncoder(
            n_perturbations=n_perturbations,
            latent_dim=c.perturbation_dim,
            hidden_dims=[64],
        )

        # Basal + covariate encoders
        self.basal_encoder = BasalEncoder(
            n_genes=n_genes,
            basal_dim=c.basal_dim,
            hidden_dims=[512, 256],
        )
        self.covariate_encoder = CovariateEncoder(
            n_covariates=n_covariates,
            covariate_dim=c.covariate_dim,
        )

        # Decoder
        latent_total = c.basal_dim + c.perturbation_dim + c.covariate_dim
        self.decoder = CellStateDecoder(
            input_dim=latent_total,
            n_genes=n_genes,
            hidden_dims=[256, 512],
        )

        # MoA heads (both)
        self.moa_head = MoAClassificationHead(
            perturbation_dim=c.perturbation_dim,
            n_moa_classes=n_moa_classes,
        )
        self.metric_moa_head = MetricMoAHead(
            perturbation_dim=c.perturbation_dim,
            n_moa_classes=n_moa_classes,
            temperature=c.temperature,
            momentum=c.prototype_update_momentum,
        )

        # Adversarial discriminator
        self.discriminator = AdversarialDiscriminator(
            perturbation_dim=c.perturbation_dim,
            n_covariates=n_covariates,
        )

        # Contrastive loss
        self.contrastive_loss = MoAContrastiveLoss(temperature=c.temperature)

    def encode_drug(self, fingerprint: torch.Tensor, dose: torch.Tensor):
        """Encode drug perturbation via rFCFP fingerprint."""
        return self.drug_encoder(fingerprint, dose)

    def encode_crispr(self, perturb_idx: torch.Tensor):
        """Encode CRISPR perturbation via gene index."""
        return self.crispr_encoder(perturb_idx)

    def encode(self, x: torch.Tensor, perturb_type: str = "drug",
               fingerprint: torch.Tensor = None, perturb_idx: torch.Tensor = None,
               dose: torch.Tensor = None, covariate_idx: torch.Tensor = None):
        """Encode inputs into latent space."""
        z_basal = self.basal_encoder(x)
        z_covariate = self.covariate_encoder(covariate_idx)

        if perturb_type == "drug":
            z_perturb = self.encode_drug(fingerprint, dose)
        else:
            z_perturb = self.encode_crispr(perturb_idx)

        return z_basal, z_perturb, z_covariate

    def decode(self, z_basal, z_perturb, z_covariate):
        z = torch.cat([z_basal, z_perturb, z_covariate], dim=-1)
        return self.decoder(z)

    def forward(self, x: torch.Tensor, fingerprint: torch.Tensor,
                dose: torch.Tensor, covariate_idx: torch.Tensor,
                perturb_idx: torch.Tensor = None):
        """
        Forward pass using drug (rFCFP) encoding.

        Key design (v2.1): z_perturb is DETACHED from the reconstruction path.
        The drug_encoder only receives gradients from MoA/contrastive losses,
        preventing reconstruction loss (MSE ~38) from overwhelming the MoA signal.
        The decoder still reconstructs using the perturbation vector value but
        no gradient flows back through drug_encoder via reconstruction.

        Args:
            x: [batch, n_genes] gene expression
            fingerprint: [batch, fingerprint_bits] FCFP bit vectors
            dose: [batch, 1] dose values
            covariate_idx: [batch] cell line indices
            perturb_idx: [batch] drug indices (for CRISPR fallback, unused for drug mode)
        """
        z_basal, z_perturb, z_covariate = self.encode(
            x, perturb_type="drug", fingerprint=fingerprint,
            dose=dose, covariate_idx=covariate_idx
        )
        # Detach z_perturb from recon path so drug_encoder only gets MoA gradients
        x_recon = self.decode(z_basal, z_perturb.detach(), z_covariate)
        moa_logits = self.moa_head(z_perturb)
        metric_logits = self.metric_moa_head(z_perturb)
        return x_recon, moa_logits, metric_logits, z_perturb, z_basal, z_covariate

    def compute_loss(self, x: torch.Tensor, fingerprint: torch.Tensor,
                     dose: torch.Tensor, covariate_idx: torch.Tensor,
                     moa_labels: torch.Tensor, n_covariates: int,
                     perturb_idx: torch.Tensor = None):
        """
        Compute total loss with both classification and metric heads.

        L = w1*L_recon + w2*L_cls + w3*L_metric + w4*L_adv + w5*L_contrastive
        """
        c = self.config
        x_recon, moa_logits, metric_logits, z_perturb, z_basal, z_covariate = self.forward(
            x, fingerprint, dose, covariate_idx, perturb_idx
        )

        # Update metric prototypes (EMA)
        if self.training:
            self.metric_moa_head.update_prototypes(z_perturb.detach(), moa_labels)

        # 1. Reconstruction loss
        loss_recon = F.mse_loss(x_recon, x)

        # 2. MoA classification loss (supervised, seen classes)
        loss_cls = F.cross_entropy(moa_logits, moa_labels)

        # 3. Metric MoA loss (prototype-based, better generalization)
        loss_metric = F.cross_entropy(metric_logits, moa_labels)

        # 4. Adversarial loss
        cov_pred = self.discriminator(z_perturb.detach())
        loss_adv_disc = F.cross_entropy(cov_pred, covariate_idx)
        cov_pred_enc = self.discriminator(z_perturb)
        loss_adv_enc = -F.cross_entropy(cov_pred_enc, covariate_idx)

        # 5. Contrastive loss
        loss_contrastive = self.contrastive_loss(z_perturb, moa_labels)

        # Total loss
        total_loss = (c.lambda_recon * loss_recon
                      + c.lambda_classification * loss_cls
                      + c.lambda_classification * loss_metric  # same weight
                      + c.lambda_adversarial * loss_adv_enc
                      + c.lambda_contrastive * loss_contrastive)

        loss_dict = {
            'total': total_loss,
            'recon': loss_recon,
            'classification': loss_cls,
            'metric': loss_metric,
            'adv_disc': loss_adv_disc,
            'adv_enc': loss_adv_enc,
            'contrastive': loss_contrastive,
        }

        return total_loss, loss_dict

    def predict_moa(self, x: torch.Tensor, fingerprint: torch.Tensor,
                    dose: torch.Tensor, covariate_idx: torch.Tensor,
                    top_k: list = None, use_metric: bool = True):
        """Predict MoA with top-k accuracy evaluation."""
        top_k = top_k or [1, 3, 5]
        with torch.no_grad():
            _, moa_logits, metric_logits, z_perturb, _, _ = self.forward(
                x, fingerprint, dose, covariate_idx
            )
            if use_metric:
                probs = F.softmax(metric_logits, dim=-1)
            else:
                probs = F.softmax(moa_logits, dim=-1)
            topk_vals, topk_idx = probs.topk(max(top_k), dim=-1)
        return probs, topk_idx, z_perturb

    def predict_zero_shot(self, z_query: torch.Tensor,
                          reference_z: torch.Tensor,
                          reference_labels: torch.Tensor,
                          top_k: int = 5):
        """
        Zero-shot MoA prediction via nearest-neighbor in latent space.

        For leave-MoA-out: query embeddings are matched to reference embeddings
        whose MoA labels are known. No classification head needed.
        """
        return self.metric_moa_head.predict_zero_shot(
            z_query, reference_z, reference_labels, top_k
        )

    def cross_perturbation_match(self, z_query: torch.Tensor,
                                  z_reference: torch.Tensor,
                                  reference_labels: torch.Tensor,
                                  top_k: int = 5):
        """Find most similar reference perturbations for a query perturbation."""
        z_query = F.normalize(z_query, dim=-1)
        z_reference = F.normalize(z_reference, dim=-1)
        sim_matrix = torch.mm(z_query, z_reference.t())
        topk_sim, topk_idx = sim_matrix.topk(top_k, dim=-1)
        matched_moa = reference_labels[topk_idx]
        return topk_idx, topk_sim, matched_moa
